FROM python:3.14-slim
WORKDIR /app
COPY frontend-requirements.txt .
RUN pip install --no-cache-dir -r frontend-requirements.txt 
COPY . .
EXPOSE 8501
CMD ["streamlit","run","quiz_app.py","--server.address=0.0.0.0","--server.port=8501"]