apiVersion: v1
kind: Service
metadata:
  name: capitals-quiz-backend-service
spec:
  selector:
    sector: quiz-backend
    app: capitals
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000